version: '3'
services:
    db:
        env_file: ./.dbenv
        volumes:
            - ./backups:/backups
            - ./pg_data:/var/lib/postgresql
        restart: always
        image: postgres:10
        working_dir: /app
        ports:
            - 5434:5432
    redis:
        image: redis:latest
        volumes:
          - ./redis_data:/data
        ports:
          - "6379"
    user-service:
        build:
          context: .
          dockerfile: ./docker/app.docker/Dockerfile.prod
        env_file: ./.flaskenv
        command: ["/entrypoint.prod.sh"]
        volumes:
          # TODO копировать все в Docker файле
          - ./flags:/flags
          - sockets:/sockets
        ports:
          - 5000:5000
        depends_on:
          - db
          - redis
    nginx:
            image: nginx
            volumes:
                - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                - sockets:/sockets
            ports:
                - 8033:80
            depends_on:
                - user-service

volumes:
    sockets:

